name: Astronomer CI - Create Preview

on:
  create:
    branches:
      - '**'
      - '!main'

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
    - name: Create Deployment Preview
      uses: astronomer/deploy-action@v0.4
      with:
        action: create-deployment-preview
        deployment-id: ${{ vars.DEPLOYMENT_ID }}
        parse: true