name: Astronomer CI - Delete Preview

on:
  delete:
    branches:
      - '**'
      - '!main'

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Deployment Preview
      uses: astronomer/deploy-action@v0.4
      with:
        action: delete-deployment-preview
        deployment-id: ${{ vars.DEPLOYMENT_ID }}
        preview-name: staging-${{ github.ref_name }}