name: Astronomer CI - Deploy Prod

on:
  push:
    branches:
      - main

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to Production Environment
      uses: astronomer/deploy-action@v0.4
      with:
        deployment-id: ${{ vars.DEPLOYMENT_ID }}
        parse: true
        pytest: true