name: Astronomer CI - Deploy code

on:
  workflow_dispatch:
    inputs:
      deploymentId:
        description: "Deployment ID"
        required: true
        type: string
      apiToken:
        description: "Astro API Token"
        required: true
        type: string
  push:
    branches:
      - main

env:
  ASTRO_API_TOKEN: ${{ inputs.apiToken || secrets.ASTRO_API_TOKEN }}
  DEPLOYMENT_ID: ${{ inputs.deploymentId || vars.DEPLOYMENT_ID }}

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to Production Environment
      uses: astronomer/deploy-action@v0.2
      with:
        deployment_id: ${{ secrets.PROD_DEPLOYMENT_ID }}
        astro_api_token: ${{ env.ASTRO_API_TOKEN }}
